//End point para autentificarse como administrador y generar token
###
POST http://localhost:5000/auth

content-Type: application/x-www-form-urlencoded
{
    "correo":"juan.perez.montero@gmail.com",
    "pass":"juan1234"
}



#End point para visualizar todas las devoluciones de los usuarios que tienen que retornar o que retornaron los libros##
GET http://localhost:5000/api/devolutions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJqdWFuLnBlcmV6Lm1vbnRlcm9AZ21haWwuY29tIiwicGFzcyI6Imp1YW4xMjM0IiwiaWF0IjoxNjIyNTEzNzU3LCJleHAiOjE2MjI1MTczNTd9.u8kv25JQriUcCq4hAFFcwuznPOhBKo1YuynQPOHQgN4

###
GET http://localhost:5000/api/devolutions?accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJqdWFuLnBlcmV6Lm1vbnRlcm9AZ21haWwuY29tIiwicGFzcyI6Imp1YW4xMjM0IiwiaWF0IjoxNjIyNTEzNzU3LCJleHAiOjE2MjI1MTczNTd9.u8kv25JQriUcCq4hAFFcwuznPOhBKo1YuynQPOHQgN4



End point para visualizar todos libros para prestarse
###
GET http://localhost:5000/api/books
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJqdWFuLnBlcmV6Lm1vbnRlcm9AZ21haWwuY29tIiwicGFzcyI6Imp1YW4xMjM0IiwiaWF0IjoxNjIyNTEzNzU3LCJleHAiOjE2MjI1MTczNTd9.u8kv25JQriUcCq4hAFFcwuznPOhBKo1YuynQPOHQgN4